name: Terraform Deploy (GitHub-hosted Runner)
on:
  push:
    branches:
     - main
  
jobs:
 terraform:
  name: Terraform-Deploy
  runs-on: ubuntu-latest

  defaults:
      run:
        working-directory: terraform-projects 

  steps:
    - name: checkout-code
      uses: actions/checkout@v4

    - name: aws cred
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        access_key = ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        region     = "us-east-1"
        
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - name: terraform-init
      run: terraform init  

    - name: terraform-plan
      run: terraform plan
      
    - name: terraform apply -auto-approve
      run: |
        terraform apply -auto-approve
        echo "Sleeping for 5 minutes..."
        sleep 300
      
    - name: terraform destroy
      run: terraform destroy -auto-approve
