name: Terraform Deploy (GitHub-hosted Runner)

on:
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    name: Detect Changed Namespace Directories
    runs-on: ubuntu-latest
    outputs:
      changed_namespaces: ${{ steps.set-vars.outputs.changed_namespaces }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we get full commit history

      - name: Get Changed Namespace Directories
        id: set-vars
        run: |
          echo "Fetching base branch..."
          git fetch origin main

          echo "Detecting changed directories..."
          changed_dirs=$(git diff --name-only origin/main...HEAD | grep '^terraform-projects/modules/' || true)

          # Extract only unique namespace paths like terraform-projects/modules/foo/bar
          namespaces=$(echo "$changed_dirs" | awk -F'/' '{print $1"/"$2"/"$3}' | sort -u | grep -v '^$')

          echo "Changed namespaces:"
          echo "$namespaces"

          # Convert to JSON array
          json_array=$(echo "$namespaces" | jq -R . | jq -s .)

          echo "changed_namespaces=$json_array" >> "$GITHUB_OUTPUT"

  terraform:
    name: Terraform Plan
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.changed_namespaces != '[]'
    strategy:
      matrix:
        namespace: ${{ fromJson(needs.detect-changes.outputs.changed_namespaces) }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.namespace }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
